#include "grayscale_filter.h"
#include "blur_filter.h"
#include "composed_filter.h"
#include "invert_filter.h"
#include "hflip_filter.h"
#include "vflip_filter.h"
#include "color_filters.h"
#include "mosaic_filter.h"